# Generated by Django 5.1.4 on 2025-01-13 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_alter_cliente_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='clientes.cpf'),
        ),
    ]
